# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "80_core.ipynb",
         "USBVideoStream": "81_USB_video_stream.ipynb"}

modules = ["core.py",
           "USB_video_stream.py"]

git_url = "https://github.com/johnnewto/FLIRCam/tree/master/"

def custom_doc_links(name): return None
