# AUTOGENERATED! DO NOT EDIT! File to edit: dev/80_core.ipynb (unless otherwise specified).

__all__ = ['show_img', 'plot_images']

# Cell
import matplotlib.pyplot as plt

# Cell
def show_img(im, figsize=None, ax=None, alpha=None, label=None, mode=None, axis_on=False, title=None, cmap=None, vmin=0, vmax=None):
    if not ax: fig, ax = plt.subplots(figsize=figsize)
    ax.imshow(im, alpha=alpha, cmap=cmap, vmin=vmin, vmax=vmax)
    if not axis_on:
        ax.set_axis_off()
    if label: ax.legend()
    if title: ax.set_title(title)
    return ax

# Cell
def plot_images(img_dict, figsize=None):
    ' plot numpy images side by side'
    fig, axes = plt.subplots(1, len(img_dict), figsize=figsize)
    for i, id in enumerate(img_dict.items()):
        show_img(id[1], ax=axes[i], title=id[0])
    plt.tight_layout()
